# Generated by Django 6.0.6 on 2026-07-11 10:46

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], max_length=20)),
                ('party_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_deadline', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_due_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Due Account',
                'verbose_name_plural': 'Due Accounts',
                'ordering': ['-due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_due_payments', to=settings.AUTH_USER_MODEL)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.dueaccount')),
            ],
            options={
                'verbose_name': 'Due Payment',
                'verbose_name_plural': 'Due Payments',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('both', 'Both')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account Category',
                'verbose_name_plural': 'Account Categories',
                'ordering': ['category_type', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category_type'), name='finance_category_type_name_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.transactioncategory')),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dueaccount',
            index=models.Index(fields=['due_date'], name='finance_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dueaccount',
            index=models.Index(fields=['due_type'], name='finance_due_type_idx'),
        ),
        migrations.AddIndex(
            model_name='dueaccount',
            index=models.Index(fields=['due_deadline'], name='finance_due_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='dueaccount',
            index=models.Index(fields=['due_type', 'due_date'], name='finance_due_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dueaccount',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', Decimal('0.00'))), name='finance_due_original_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='duepayment',
            index=models.Index(fields=['payment_date'], name='finance_payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='duepayment',
            index=models.Index(fields=['payment_method'], name='finance_payment_method_idx'),
        ),
        migrations.AddConstraint(
            model_name='duepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='finance_due_payment_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_date'], name='finance_txn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_type'], name='finance_txn_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['payment_method'], name='finance_txn_method_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='finance_txn_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='finance_cash_transaction_amount_gt_zero'),
        ),
    ]
