# Generated by Django 6.0.6 on 2026-07-11 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('due_payment', 'Due Payment'), ('opening_balance', 'Opening Balance')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='duepayment',
            name='cash_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='due_payment', to='finance.cashtransaction'),
        ),
    ]
