# Generated by Django 6.0.3 on 2026-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_icon_class'),
        ('purchase', '0002_purchaseitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='category.brand'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='category.category'),
        ),
    ]
