# Generated by Django 6.0.6 on 2026-07-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_product_low_stock_threshold_product_stock_quantity_and_more'),
        ('purchase', '0003_alter_purchase_brand_alter_purchase_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStockApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_stock_applications', to='category.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_applications', to='purchase.purchase')),
                ('purchase_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_application', to='purchase.purchaseitem')),
            ],
            options={
                'verbose_name': 'Purchase Stock Application',
                'verbose_name_plural': 'Purchase Stock Applications',
            },
        ),
    ]
