# Generated by Django 6.0.1 on 2026-04-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
    ]
