# Generated by Django 6.0.3 on 2026-04-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_product_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reviewer_name", models.CharField(max_length=120)),
                ("reviewer_email", models.EmailField(blank=True, max_length=254)),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("rating", models.PositiveSmallIntegerField()),
                ("verified_purchase", models.BooleanField(default=False)),
                ("helpful_yes", models.PositiveIntegerField(default=0)),
                ("helpful_no", models.PositiveIntegerField(default=0)),
                ("review_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="category.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "db_table": "category_product_review",
                "ordering": ["-review_date", "-id"],
            },
        ),
    ]
