# Generated by Django 6.0.1 on 2026-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, default='fa fa-tag', max_length=64),
        ),
    ]
