# Generated by Django 6.0.6 on 2026-07-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_brand_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='product_low_threshold_nonnegative'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening_stock', 'Opening Stock'), ('manual_adjustment', 'Manual Adjustment'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('purchase_return', 'Purchase Return'), ('sale_return', 'Sale Return'), ('order_cancellation', 'Order Cancellation')], max_length=32)),
                ('quantity_change', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='category.product')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'category_stock_transaction',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='stocktxn_product_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change__gt', 0), ('quantity_change__lt', 0), _connector='OR'), name='stocktxn_quantity_change_nonzero')],
            },
        ),
    ]
