# Generated by Django 6.0.3 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0011_product_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
