# Generated by Django 6.0.3 on 2026-03-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0004_seed_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_title',
        ),
    ]
