# Generated by Django 6.0.3 on 2026-03-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0005_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-is_active', '-sort_order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
