# Generated by Django 6.0.3 on 2026-03-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0009_ensure_seed_subcategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='sort_order',
        ),
    ]
