# Generated by Django 6.0.3 on 2026-03-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0010_alter_subcategory_options_remove_subcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
