# Generated by Django 6.0.1 on 2026-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitepages', '0013_move_catalog_models_to_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('title_highlight', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('primary_button_label', models.CharField(blank=True, max_length=80)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('content_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
