# Generated by Django 6.0.1 on 2026-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0015_alter_heroslide_content_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=20),
        ),
    ]
