# Generated by Django 6.0.1 on 2026-04-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0016_alter_heroslide_content_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('logo_primary_text', models.CharField(blank=True, default='SB', max_length=80)),
                ('logo_secondary_text', models.CharField(blank=True, default='Revo', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payment_heading', models.CharField(blank=True, default='We Accept', max_length=120)),
                ('copyright_text', models.CharField(blank=True, default='© 2024 SB Revo. All rights reserved.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('placement', models.CharField(choices=[('main', 'Main Column'), ('bottom', 'Bottom Row')], default='main', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to='sitepages.footercontent')),
            ],
            options={
                'verbose_name': 'Footer Link Group',
                'verbose_name_plural': 'Footer Link Groups',
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='sitepages.footerlinkgroup')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('icon_class', models.CharField(default='fab fa-cc-visa', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='sitepages.footercontent')),
            ],
            options={
                'verbose_name': 'Footer Payment Method',
                'verbose_name_plural': 'Footer Payment Methods',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('icon_class', models.CharField(default='fab fa-facebook-f', max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='sitepages.footercontent')),
            ],
            options={
                'verbose_name': 'Footer Social Link',
                'verbose_name_plural': 'Footer Social Links',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
