# Generated by Django 6.0.1 on 2026-04-29 07:18

from django.db import migrations, models


def seed_homepage_promo_banners(apps, schema_editor):
    HomepagePromoBanner = apps.get_model("sitepages", "HomepagePromoBanner")
    banners = [
        {
            "name": "Women's Fashion Collection",
            "placement": "large",
            "eyebrow": "New Arrivals",
            "title": "Women's Fashion Collection",
            "image_url": "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=700&h=350&fit=crop",
            "button_label": "Shop Now",
            "button_url": "/products/",
            "sort_order": 1,
            "is_active": True,
        },
        {
            "name": "Smart Watches",
            "placement": "small",
            "eyebrow": "Up to 50% Off",
            "title": "Smart Watches",
            "image_url": "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&h=200&fit=crop",
            "button_label": "Discover",
            "button_url": "/products/",
            "use_dark_overlay": True,
            "sort_order": 1,
            "is_active": True,
        },
        {
            "name": "Sport Collection",
            "placement": "small",
            "eyebrow": "Best Sellers",
            "title": "Sport Collection",
            "image_url": "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=200&fit=crop",
            "button_label": "Explore",
            "button_url": "/products/",
            "sort_order": 2,
            "is_active": True,
        },
    ]

    for banner in banners:
        HomepagePromoBanner.objects.get_or_create(
            name=banner["name"],
            defaults=banner,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0024_keep_single_footer_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('placement', models.CharField(choices=[('large', 'Large Banner'), ('small', 'Small Banner')], default='small', max_length=20)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_banners/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('use_dark_overlay', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Promo Banner',
                'verbose_name_plural': 'Homepage Promo Banners',
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_homepage_promo_banners, migrations.RunPython.noop),
    ]
