# Generated by Codex on 2026-06-10

from django.db import migrations


FOOTER_MODEL_NAMES = (
    "footerpaymentmethod",
    "footersociallink",
    "footerlink",
    "footerlinkgroup",
    "footercontent",
)


def remove_footer_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="sitepages", model__in=FOOTER_MODEL_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sitepages", "0025_homepagepromobanner"),
    ]

    operations = [
        migrations.DeleteModel(name="FooterPaymentMethod"),
        migrations.DeleteModel(name="FooterSocialLink"),
        migrations.DeleteModel(name="FooterLink"),
        migrations.DeleteModel(name="FooterLinkGroup"),
        migrations.DeleteModel(name="FooterContent"),
        migrations.RunPython(remove_footer_content_types, migrations.RunPython.noop),
    ]
