# Generated by Django 6.0.3 on 2026-06-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sitepages", "0026_remove_footer_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedCheckout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("full_name", models.CharField(blank=True, max_length=150, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=120, null=True)),
                ("area_thana", models.CharField(blank=True, max_length=120, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("delivery_area", models.CharField(blank=True, max_length=40, null=True)),
                ("cart_items", models.JSONField(default=list)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("shipping_charge", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="checkout_page", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abandoned_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abandoned Checkout",
                "verbose_name_plural": "Abandoned Checkouts",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "status", "updated_at"], name="sitepages_ac_user_idx"),
                    models.Index(fields=["session_key", "status", "updated_at"], name="sitepages_ac_session_idx"),
                ],
            },
        ),
    ]
