# Generated by Django 6.0.6 on 2026-07-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_product_low_stock_threshold_product_stock_quantity_and_more'),
        ('sitepages', '0027_abandonedcheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStockApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_applications', to='sitepages.order')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_application', to='sitepages.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_stock_applications', to='category.product')),
            ],
            options={
                'verbose_name': 'Order Stock Application',
                'verbose_name_plural': 'Order Stock Applications',
            },
        ),
    ]
