# Generated by Django 6.0.6 on 2026-07-25 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_imported_order_status_history(apps, schema_editor):
    Order = apps.get_model("sitepages", "Order")
    OrderStatusHistory = apps.get_model("sitepages", "OrderStatusHistory")

    for order in Order.objects.all().iterator():
        OrderStatusHistory.objects.create(
            order_id=order.pk,
            status=order.status,
            changed_at=order.updated_at or order.created_at or order.order_date,
            note="Imported current status; earlier status changes were not recorded.",
            source="imported",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0028_orderstockapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('checkout', 'Checkout'), ('dashboard', 'Dashboard'), ('payment', 'Payment'), ('shipment', 'Shipment'), ('api', 'API'), ('system', 'System'), ('imported', 'Imported')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='sitepages.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status History',
                'ordering': ['changed_at', 'id'],
                'indexes': [models.Index(fields=['order', 'changed_at'], name='sitepages_o_order_i_62b138_idx')],
            },
        ),
        migrations.RunPython(create_imported_order_status_history, migrations.RunPython.noop),
    ]
