# Generated by Django 6.0.6 on 2026-07-25 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0029_order_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'status', 'changed_at'], name='sitepages_o_order_i_062f86_idx'),
        ),
    ]
