# Generated by Django 6.0.6 on 2026-07-25 12:22

from django.db import migrations, models


def convert_processing_orders_to_confirmed(apps, schema_editor):
    """Remove only the active legacy status; keep all audit history untouched."""
    Order = apps.get_model("sitepages", "Order")
    Order.objects.filter(status="processing").update(status="confirmed")


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0031_expand_order_workflow'),
    ]

    operations = [
        migrations.RunPython(convert_processing_orders_to_confirmed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], max_length=20),
        ),
    ]
