# Generated by Django 6.0.6 on 2026-08-06

from django.db import migrations


def remove_promo_banner_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="sitepages", model="homepagepromobanner").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sitepages", "0032_remove_processing_status"),
    ]

    operations = [
        migrations.RunPython(remove_promo_banner_content_type, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="HomepagePromoBanner",
        ),
    ]
