# Generated by Django 6.0.3 on 2026-08-17 10:04

from django.db import migrations, models


def populate_company_contact_details(apps, schema_editor):
    CompanyProfile = apps.get_model("company", "CompanyProfile")
    for profile in CompanyProfile.objects.all().iterator():
        updates = {}
        if profile.company_name == "SBRevo":
            updates["company_name"] = "Next Uniq BD"
        if not profile.phone:
            updates["phone"] = "(+88) 01883 385 687"
        if not profile.email:
            updates["email"] = "nextuniqbd@gmail.com"
        if not profile.address:
            updates["address"] = "9, Shahid Tajuddin Road, Moghbazar, Dhaka, Bangladesh"
        if updates:
            CompanyProfile.objects.filter(pk=profile.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_keep_single_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(populate_company_contact_details, migrations.RunPython.noop),
    ]
