# Generated by Django 6.0.3 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [("sitepages", "0034_contactmessage")]

    operations = [
        migrations.CreateModel(
            name="MetaEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_name", models.CharField(db_index=True, max_length=64)),
                ("event_time", models.DateTimeField()),
                ("event_source_url", models.CharField(blank=True, max_length=2048)),
                ("action_source", models.CharField(default="website", max_length=32)),
                ("custom_data", models.JSONField(default=dict)),
                ("user_data", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")], db_index=True, default="pending", max_length=16)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="meta_events", to="sitepages.order")),
            ],
            options={"verbose_name": "Meta Event", "verbose_name_plural": "Meta Events", "ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="MetaOrderAttribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fbp", models.CharField(blank=True, max_length=255)),
                ("fbc", models.CharField(blank=True, max_length=255)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("client_user_agent", models.TextField(blank=True)),
                ("event_source_url", models.CharField(blank=True, max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="meta_attribution", to="sitepages.order")),
            ],
            options={"verbose_name": "Meta Order Attribution", "verbose_name_plural": "Meta Order Attributions"},
        ),
        migrations.AddIndex(model_name="metaevent", index=models.Index(fields=["status", "created_at"], name="tracking_me_status_fb522a_idx")),
        migrations.AddIndex(model_name="metaevent", index=models.Index(fields=["event_name", "created_at"], name="tracking_me_event_n_48907a_idx")),
    ]
